// Matières par série du bac sénégalais (coefficients officiels)
export const SERIES_MATIERES = {
  // ── SÉRIES SCIENTIFIQUES ──────────────────────────────────────────────────
  S1: [
    { nom: "Mathematiques", coef: 8 },
    { nom: "Physique-Chimie", coef: 8 },
    { nom: "SVT", coef: 2 },
    { nom: "Francais", coef: 3 },
    { nom: "Philosophie", coef: 2 },
    { nom: "Anglais", coef: 2 },
    { nom: "Histo-Geo", coef: 2 },
  ],
  S1A: [
    { nom: "Mathematiques", coef: 8 },
    { nom: "Physique-Chimie", coef: 8 },
    { nom: "SVT", coef: 2 },
    { nom: "Francais", coef: 3 },
    { nom: "Philosophie", coef: 2 },
    { nom: "Anglais", coef: 2 },
    { nom: "Histo-Geo", coef: 2 },
  ],
  S2: [
    { nom: "Mathematiques", coef: 5 },
    { nom: "Physique-Chimie", coef: 6 },
    { nom: "SVT", coef: 6 },
    { nom: "Francais", coef: 3 },
    { nom: "Philosophie", coef: 2 },
    { nom: "Anglais", coef: 2 },
    { nom: "Histo-Geo", coef: 2 },
  ],
  S2A: [
    { nom: "Mathematiques", coef: 5 },
    { nom: "Physique-Chimie", coef: 6 },
    { nom: "SVT", coef: 6 },
    { nom: "Francais", coef: 3 },
    { nom: "Philosophie", coef: 2 },
    { nom: "Anglais", coef: 2 },
    { nom: "Histo-Geo", coef: 2 },
  ],
  S3: [
    { nom: "Mathematiques", coef: 8 },
    { nom: "Physique-Chimie", coef: 8 },
    { nom: "Construction Mecanique", coef: 8 },
    { nom: "Analyse de Fabrication", coef: 3 },
    { nom: "Francais", coef: 3 },
    { nom: "Anglais", coef: 2 },
    { nom: "Philosophie", coef: 2 },
  ],
  S4: [
    { nom: "Mathematiques", coef: 5 },
    { nom: "Physique-Chimie", coef: 5 },
    { nom: "SVT", coef: 5 },
    { nom: "Francais", coef: 3 },
    { nom: "Philosophie", coef: 2 },
    { nom: "Anglais", coef: 2 },
    { nom: "Histo-Geo", coef: 2 },
  ],
  S5: [
    { nom: "Mathematiques", coef: 5 },
    { nom: "Physique-Chimie", coef: 5 },
    { nom: "SVT", coef: 5 },
    { nom: "Francais", coef: 3 },
    { nom: "Philosophie", coef: 2 },
    { nom: "Anglais", coef: 2 },
    { nom: "Histo-Geo", coef: 2 },
  ],
  // ── SÉRIES LITTÉRAIRES ────────────────────────────────────────────────────
  L1A: [
    { nom: "Francais", coef: 6 },
    { nom: "Philosophie", coef: 6 },
    { nom: "Grec ou Latin", coef: 5 },
    { nom: "Latin ou Arabe", coef: 5 },
    { nom: "Histo-Geo", coef: 2 },
    { nom: "Anglais", coef: 2 },
    { nom: "Mathematiques", coef: 2 },
  ],
  L1B: [
    { nom: "Francais", coef: 6 },
    { nom: "Philosophie", coef: 6 },
    { nom: "Latin ou Arabe", coef: 5 },
    { nom: "Anglais", coef: 3 },
    { nom: "Langue Vivante 2", coef: 2 },
    { nom: "Histo-Geo", coef: 2 },
    { nom: "Mathematiques", coef: 2 },
  ],
  L2: [
    { nom: "Philosophie", coef: 6 },
    { nom: "Histo-Geo", coef: 6 },
    { nom: "Francais", coef: 5 },
    { nom: "Anglais", coef: 4 },
    { nom: "Mathematiques", coef: 2 },
    { nom: "Langue Vivante 2 ou Economie", coef: 2 },
    { nom: "Sciences Naturelles", coef: 2 },
  ],
  LA: [
    { nom: "Philosophie", coef: 6 },
    { nom: "Langue et Litterature Arabes", coef: 6 },
    { nom: "Histo-Geo", coef: 4 },
    { nom: "Francais", coef: 3 },
    { nom: "Civilisation Arabo-Islamique", coef: 2 },
    { nom: "Anglais", coef: 2 },
    { nom: "Mathematiques", coef: 2 },
  ],
  // ── SÉRIES ÉCONOMIQUES ET TECHNIQUES ─────────────────────────────────────
  G: [
    { nom: "Economie", coef: 5 },
    { nom: "Etude de Cas", coef: 5 },
    { nom: "Mathematiques", coef: 4 },
    { nom: "Francais", coef: 3 },
    { nom: "Anglais", coef: 2 },
    { nom: "Philosophie", coef: 2 },
  ],
  STEG: [
    { nom: "Gestion Comptable et Financiere", coef: 6 },
    { nom: "Sciences Economiques et Sociales", coef: 6 },
    { nom: "Mathematiques", coef: 5 },
    { nom: "Francais", coef: 3 },
    { nom: "Management des Organisations", coef: 2 },
    { nom: "Droit", coef: 2 },
    { nom: "Informatique de Gestion", coef: 2 },
    { nom: "Anglais", coef: 2 },
    { nom: "Philosophie", coef: 2 },
  ],
  STIDD: [
    { nom: "Mathematiques", coef: 5 },
    { nom: "Physique-Chimie", coef: 5 },
    { nom: "Technol. Gen et Autom.", coef: 5 },
    { nom: "Francais", coef: 3 },
    { nom: "Anglais", coef: 2 },
    { nom: "Philosophie", coef: 2 },
  ],
  // ── SÉRIES TECHNIQUES ─────────────────────────────────────────────────────
  T1: [
    { nom: "Mathematiques", coef: 5 },
    { nom: "Analyse de Fabrication et Outillage", coef: 6 },
    { nom: "Mecanique", coef: 4 },
    { nom: "Construction Mecanique", coef: 4 },
    { nom: "Technologie et Automatisme", coef: 2 },
    { nom: "Epreuve Pratique Atelier", coef: 4 },
    { nom: "Technique d'Expression et de Communication", coef: 3 },
    { nom: "Anglais", coef: 2 },
  ],
  T2: [
    { nom: "Mathematiques", coef: 5 },
    { nom: "Electrotechnique-Electronique", coef: 6 },
    { nom: "Construction Electromecanique", coef: 3 },
    { nom: "Analyse des Systemes Electriques", coef: 2 },
    { nom: "Technique d'Expression et de Communication", coef: 3 },
    { nom: "Anglais", coef: 2 },
  ],
  F6: [
    { nom: "Chimie", coef: 5 },
    { nom: "Physique", coef: 4 },
    { nom: "Mathematiques", coef: 4 },
    { nom: "Technique de Laboratoire Chimie", coef: 3 },
    { nom: "TP de Chimie", coef: 4 },
    { nom: "TP de Physique", coef: 3 },
    { nom: "Montage d'Appareils", coef: 3 },
    { nom: "Francais", coef: 3 },
    { nom: "Anglais", coef: 2 },
  ],
};

export const MENTIONS = [
  { value: "Passable" },
  { value: "Assez Bien" },
  { value: "Bien" },
  { value: "Tres Bien" },
];
